name: CI

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Run scalafix and scalafmt
        run: sbt 'scalafmtSbtCheck; scalafmtCheckAll;'

  ci:
    runs-on: ubuntu-latest
    steps:
      - run: env
        shell: bash
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          check-latest: true

      - name: Compile code
        shell: bash
        run: sbt 'clean;+Test/compile;+publishLocal'
